### ISSUE TITLE
Don't use "model" to describe hyperparameter struct.

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/LearnAPI.jl#12]
Inconsistent with use in Statistics has raised objections. See e.g. https://discourse.julialang.org/t/ann-learnapi-jl-proposal-for-a-basement-level-machine-learning-api/

The question is what to call a struct whose:

-  name represents a machine learning algorithm (such as decision tree classifier), and 
-  whose fields represent the hyperparameters

Suggestions include `hyper` `options`, `strategy`, `algorithm`

**Comment by davidbp** [comment]
According to Microsoft  documentation ```A machine learning model is a file that has been trained to recognize certain types of patterns. You train a model over a set of data, providing it an algorithm that it can use to reason over and learn from those data.
```

**Comment by ablaom** [comment]
> Is Learner fitting at all?

I like "learner" and I've seen "learner" used in ML papers to refer to the unfitted object. But MLR/MLR3 uses it for the class that also stores learned parameters.

**Comment by ablaom** [comment]
After further thought (and I got as far as writing a new PR) I am less fond of "learner". The problem is that plenty of machine learning algorithms don't really learn (don't generalize to new data).

We've had a fair bit of discussion about this here and in other threads. I think consensus is impossible and have decided to go with "algorithm".

**Comment by KronosTheLate** [comment]
> We've had a fair bit of discussion about this here and in other threads. I think consensus is impossible and have decided to go with "algorithm".

Fair enough. Consensus indeed seems impossible, and debating naming is not well spent time.

**Comment by ablaom** [comment]
Re-opening. 

What are people's preferences? "learner" or "algorithm"? Please vote here: https://discourse.julialang.org/t/ann-learnapi-jl-proposal-for-a-basement-level-machine-learning-api/93048/31?u=ablaom

**Comment by davidbp** [comment]
From the provided options

**Comment by ablaom** [comment]
After a poll at https://discourse.julialang.org/t/ann-learnapi-jl-proposal-for-a-basement-level-machine-learning-api/93048/61, I will change "algorithm" to "stategy".

**Comment by ablaom** [comment]
With the greatest respect for the alternatives presented, I'm sticking with "algorithm". After many re-workings of the docs, this creates the least cognitive dissonance for me personally, by a considerable amount, despite not being my original first choice.

**Comment by KronosTheLate** [comment]
In the end, whoever rolls up their sleeves gets the final say. It is really important that the devs are not bent into shape in a way that decreases their (your) interest in working on the project! Thanks for making a huge effort in finding a suitable name, and trying to take everyone's opinions into account.
