### ISSUE TITLE
Allow multiple target proxy support with `predict` dispatching on the proxy.

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/LearnAPI.jl#14]
https://discourse.julialang.org/t/ann-learnapi-jl-proposal-for-a-basement-level-machine-learning-api/93048/12?u=ablaom

@CameronBieganek @juliohm

**Comment by ablaom** [comment]
In this way we can also get rid of the separate `predict_joint`  -  and even `transform` and `inverse_transform  by adding special `TargetProxy` types for them.

**Comment by CameronBieganek** [comment]
Hmm, I'm not sure about getting rid of `transform`.

**Comment by ablaom** [comment]
closed as done
